
kind: Job
apiVersion: batch/v1
metadata:
  name: trinity-tmp
  namespace: sw77-hpc-test
  labels:
    app: trinity-tmp
    app.kubernetes.io/component: trinity-tmp
    app.kubernetes.io/instance: trinity-tmp
    app.kubernetes.io/name: trinity-tmp
    app.openshift.io/runtime-namespace: sw77-hpc-test

spec:
  parallelism: 20
  completions: 20
  selector:
    matchLabels:
  template:
    metadata:
      labels:
        app: trinity-tmp
        deployment: trinity-tmp
    spec:
      volumes:
        - name: sw77-shared
          persistentVolumeClaim:
            claimName: sw77-shared
        - name: sw77-tmp
          emptyDir:
            sizeLimit: 100Gi
      containers:
        - resources:
            limits:
              cpu: '48'
              memory: 48Gi
            requests:
              cpu: '48'
              memory: 20Gi
          name: trinity-tmp
          volumeMounts:
            - name: sw77-shared
              mountPath: /work
            - mountPath: /scratch
              name: sw77-tmp
          image: >-
            registry.cloud.rt.nyu.edu/sw77/trinity
          env:
            - name: TZ
              value: America/New_York
          command:
            - /bin/bash
            - '-c'
            - |
              export TZ="America/New_York" && \
              UUID=$(hostname -s) && \
              work=/work/trinity-tmp-test/${UUID} && \
              mkdir -p ${work} && cd ${work} && rm -rf * && \
              cd /scratch && \
              Trinity \
              --no_version_check \
              --seqType fq \
              --max_memory 20G \
              --CPU 40 \
              --bflyGCThreads 32 \
              --bflyCPU 48 \
              --inchworm_cpu 48 \
              --output $(pwd)/trinity \
              --left /work/save/left.fastq \
              --right /work/save/right.fastq > ${work}/out.log 2>&1 && \
              cp -rp $(pwd)/trinity ${work}
      restartPolicy: Never

