
kind: Job
apiVersion: batch/v1
metadata:
  name: ubuntu
  namespace: sw77-hpc-test
  labels:
    app: ubuntu
    app.kubernetes.io/component: ubuntu
    app.kubernetes.io/instance: ubuntu
    app.kubernetes.io/name: ubuntu
    app.openshift.io/runtime-namespace: sw77-hpc-test

spec:
  parallelism: 1
  completions: 1
  completionMode: Indexed
  selector:
    matchLabels:
  template:
    metadata:
      labels:
        app: ubuntu
        deployment: ubuntu
    spec:
      volumes:
        - name: work
          persistentVolumeClaim:
            claimName: sw77-shared
        - name: tmp
          emptyDir:
            sizeLimit: 20Gi
        - name: license
          emptyDir:
            sizeLimit: 1Gi
      containers:
        - resources:
            limits:
              cpu: '48'
              memory: 96Gi
            requests:
              cpu: '4'
              memory: 8Gi
          name: ubuntu
          volumeMounts:
            - name: work
              mountPath: /home
            - name: tmp
              mountPath: /tmp
            - name: license
              mountPath: /license
          image: >-
             registry.cloud.rt.nyu.edu/sw77/ubuntu:24.04-20241204
          env:
            - name: TZ
              value: America/New_York
            - name: HOME
              value: /home/wang
            - name: MY_POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''batch.kubernetes.io/job-completion-index'']'
          command:
            - /bin/bash
            - '-c'
            - |
              hostname
              sleep infinity
      restartPolicy: Never

