
kind: Job
apiVersion: batch/v1
metadata:
  name: matlab
  namespace: sw77-hpc-test
  labels:
    app: matlab
    app.kubernetes.io/component: matlab
    app.kubernetes.io/instance: matlab
    app.kubernetes.io/name: matlab
    app.openshift.io/runtime-namespace: sw77-hpc-test

spec:
  parallelism: 1
  completions: 1
  completionMode: Indexed
  ttlSecondsAfterFinished: 120
  selector:
    matchLabels:
  template:
    metadata:
      labels:
        app: matlab
        deployment: matlab
    spec:
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: sw77-shared
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
        - name: matlab
          emptyDir:
            sizeLimit: 10Mi
        - name: math-works
          emptyDir:
            sizeLimit: 10Mi
        - name: service-host
          emptyDir:
            sizeLimit: 1Mi
        - name: matlab-connector
          emptyDir:
            sizeLimit: 10Mi
      containers:
        - resources:
            limits:
              cpu: '180'
              memory: 900Gi
            requests:
              cpu: '180'
              memory: 900Gi
          name: matlab
          volumeMounts:
            - name: home
              mountPath: /home
            - name: tmp
              mountPath: /tmp
            - name: matlab
              mountPath: /home/wang/.matlab
            - name: math-works
              mountPath: /home/wang/.MathWorks
            - name: service-host
              mountPath: /home/wang/.MathWorks/ServiceHost
              readOnly: true
            - name: matlab-connector
              mountPath: /home/wang/.MATLABConnector
          image: >-
             registry.cloud.rt.nyu.edu/sw77/matlab:2024b
          env:
            - name: TZ
              value: America/New_York
            - name: HOME
              value: /home/wang
            - name: MLM_LICENSE_FILE
              value: 27000@lm2.its.nyu.edu,27000@lm3.its.nyu.edu,27000@lm4.its.nyu.edu
            - name: MATLAB_PREFDIR
              value: /tmp/matlab
            - name: MATLAB_LOG_DIR 
              value: /tmp/matlab
          command:
            - /bin/bash
            - '-c'
            - | 
              sleep infinity
              cd /home/wang/matlab-test/parfor-prefdir 
              bash run-matlab.sbatch > stdout-$(hostname -s).log 2>&1
      restartPolicy: Never

