
kind: Job
apiVersion: batch/v1
metadata:
  name: ampl
  namespace: sw77-hpc-test
  labels:
    app: ampl
    app.kubernetes.io/component: ampl
    app.kubernetes.io/instance: ampl
    app.kubernetes.io/name: ampl
    app.openshift.io/runtime-namespace: sw77-hpc-test

spec:
  parallelism: 1000
  completions: 1000
  completionMode: Indexed
  ttlSecondsAfterFinished: 120
  selector:
    matchLabels:
  template:
    metadata:
      labels:
        app: ampl
        deployment: ampl
    spec:
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: sw77-shared
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
            medium: Memory
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 20Gi
            requests:
              cpu: '1'
              memory: 2Gi
          name: ampl
          volumeMounts:
            - name: home
              mountPath: /home
            - name: tmp
              mountPath: /tmp
          image: >-
            registry.cloud.rt.nyu.edu/sw77/ampl:14.0.0-20250102
          env:
            - name: TZ
              value: America/New_York
            - name: HOME
              value: /work/wang
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: MY_POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.labels[''batch.kubernetes.io/job-completion-index'']'
          command:
            - /bin/bash
            - '-c'
            - |
              cd /home/wang/ampl-test/rc5176 && mkdir -p hpc_runs/logs
              index="00000${MY_POD_INDEX}"
              index=${index: -4}
              /home/wang/ampl-test/ampl/run-ampl.bash python3 staircase.py ${MY_POD_INDEX} > hpc_runs/logs/${index}.log 2>&1

      restartPolicy: Never
